quarkus:
  http:
    port: 8080
  reactive: false
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  hibernate-orm:
    database:
      generation: drop-and-create
  rest-client:
    free-e-api:
      url: https://free.e-api.net.pe
      connect-timeout: 5000
      read-timeout: 5000